.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/SECURITY.md, .github/pull_request_template.md, README.rst
copied from the main sqlalchemy repo github issues/pr templates code of conduct and other stuff
@zzzeek
=> add github stuff

sqlalchemy-stubs/orm/__init__.pyi, sqlalchemy-stubs/orm/relationships.pyi
Improves the annotations of the `RelationshipProperty` class constructor and attributes.
=> Flesh out `Relationship` annotations

sqlalchemy-stubs/orm/decl_api.pyi
Improves the declarative API's annotations.
Some legacy constructs are not typed.
=> Improve declarative API annotations

sqlalchemy-stubs/sql/events.pyi
=> Improve `sql.events`

sqlalchemy-stubs/sql/naming.pyi
=> Improve `sql.naming`

sqlalchemy-stubs/sql/default_comparator.pyi
Improve `sql.default_comparator` typings
=> Improve `sql.default_comparator`

sqlalchemy-stubs/sql/coercions.pyi
Improve `sql.coercions` to pass in strict mode. Depends on #22.
=> Improve `sql.coercions`

sqlalchemy-stubs/ext/asyncio/events.pyi
=> Improve `ext.asyncio.events`

sqlalchemy-stubs/sql/type_api.pyi
Fix `UserDefinedType` inheritance. Refs #55.
=> Fix `UserDefinedType` inheritance

sqlalchemy-stubs/sql/expression.pyi
Improve `sql.expression`. Depends on #40.
=> Improve `sql.expression`

sqlalchemy-stubs/ext/declarative/__init__.pyi, sqlalchemy-stubs/ext/declarative/extensions.pyi
=> Improve `ext.declarative`

.github/workflows/run-test.yaml, .github/workflows/scripts/find_version.py, .gitignore, tox.ini
=> Add test workflox and tox

sqlalchemy-stubs/sql/functions.pyi
Improve `sql.functions`. Depends on #38. Refs #68.
=> Improve `sql.functions`

sqlalchemy-stubs/types.pyi
=> Improve `types`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md
=> Improve bug report template

test/files/column_arguments.py, test/files/column_arguments2.py, test/files/mapped_assign_expression.py, tox.ini
Run test files from the test directory. Depends on https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2807 to be merged to SQLA master to succesfully run.
I also included 3 test files I used in #73 and #69
- Please include: `Fixes: #<issue …
=> Run test files from stubs directory

.github/workflows/scripts/find_version.py, .pre-commit-config.yaml, sqlalchemy-stubs/engine/create.pyi
Update to black 21.5b0 and reformat
=> Update to black 21.5b0 and reformat

sqlalchemy-stubs/engine/result.pyi
=> Improve `engine.result`

sqlalchemy-stubs/orm/relationships.pyi, test/files/relationship_order_by_ticket_77.py
=> Fix relationship.order_by multiple clauses

sqlalchemy-stubs/__init__.pyi
Add the missing field \_\_version__. Fixes #120 
Add the missing field \_\_version__
- [ X] A short code fix
=> Add missing  __version__

sqlalchemy-stubs/ext/asyncio/session.pyi, sqlalchemy-stubs/orm/session.pyi, test/files/async_stuff.py
- Please include: Fixes: #155 in the commit message
=> fix issue with _AsyncSessionProtocol

sqlalchemy-stubs/sql/elements.pyi, sqlalchemy-stubs/sql/functions.pyi, test/files/functions.py
- Please include: Fixes: #156 in the commit message
=> improve types of over in functions

sqlalchemy-stubs/sql/operators.pyi, test/files/operators.py
- Please include: Fixes: #148 in the commit message
=> improve op() typing

.github/workflows/run-test.yaml, .github/workflows/scripts/find_version.py, tox.ini
=> replace the master branch of sqlalchemy with main

.github/workflows/run-test.yaml, .github/workflows/scripts/find_version.py
=> update workflow to use python 3.10, add rel_1_4 branch to test

sqlalchemy-stubs/orm/session.pyi
The type '_T' has been defined as the 'Union[Connection, Engine]' type in the 'Session' class.
=> Fixed typing error in `session.get`.

sqlalchemy-stubs/orm/session.pyi
=> Fix variable name error
